# NewsFeed
alias stockclip="open https://www.stockclip.net/"
alias gn="open https://news.google.com"
alias feedly="open https://feedly.com/"
alias cnn="open https://www.cnn.co.jp/"
alias nabiz="open https://www.nikkei.com/international/asiabiz/?n_cid=ds_under_title"
alias nnaasia="open https://www.nna.jp/"
alias nnaeu="open https://europe.nna.jp/"
alias chuounippo="open https://japanese.joins.com/"
alias chosennippo="open http://www.chosunonline.com/"
alias bbc="open https://www.bbc.com/japanese"
alias reuters="open https://jp.reuters.com/news/world"
alias pbs="open https://www.pbs.org/newshour/"
alias wsj="open https://jp.wsj.com/"
alias hn="open https://news.ycombinator.com/"
alias news="open -n /Applications/Chrome.app/; gn; stockclip; feedly; cnnnabiz; nnaasia; nnaeu; chuounippo; chosennippo; bbc; reuters; pbs; wsj; hn"
