[[snippets]]
  description = "Show disk utilization of /"
  command = "du -h --max-depth=1 / 2>/dev/null"
  output = ""
[[snippets]]
  description = "Show disk utilization of /"
  command = "du -h --max-depth=1 / 2>/dev/null"
  output = ""
[[snippets]]
  description = "Show disk utilization of /var/* with sort"
  command = "sudo du -scm /var/* | sort -rn"
  output = ""
[[snippets]]
  description = "Check the number of cpu for Linux"
  command = "cat /proc/cpuinfo | grep processor | wc -l"
  output = ""
[[snippets]]
  description = "Reboot shell process"
  command = "exec ${SHELL} -l"
  output = ""

[[snippets]]
  description = "Delete already merged branches"
  command = "git branch --merged | grep -v '*' | xargs -I % git branch -d %"
  output = ""

[[snippets]]
  description = "Delete inactive docker processes"
  command = "docker rm $(docker ps -a --filter 'status=exited' -q)"
  output = ""
[[snippets]]
  description = "Delete unused docker images"
  command = "docker rmi $(docker images -a | awk '/^<none>/ { print $3 }')"
  output = ""
